<a href="https://colab.research.google.com/github/ShiyaoGU/PyTorch-for-Deep-Learning-Machine-Learning1/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


00.Pytorch Fundamentals

Resource notebook: https://learnpytorch.io

If you have a question: about: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

## creating tensors
Pytorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/index.html

In [3]:
# scalar
scalar  = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7, 8],[9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3,6],
                        [3,6,9,7],
                        [4,5,2,2],
                        [8,9,0,0]]])
TENSOR

tensor([[[1, 2, 3, 6],
         [3, 6, 9, 7],
         [4, 5, 2, 2],
         [8, 9, 0, 0]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 4, 4])

In [16]:
TENSOR[0]

tensor([[1, 2, 3, 6],
        [3, 6, 9, 7],
        [4, 5, 2, 2],
        [8, 9, 0, 0]])

### Random Tensors

why random tensors?
Random tensors are important becoz the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers ->look at data ->update random numbers ->look at data ->update random numbers

Torch random tensors : https://pytorch.org/docs/stable/generated/torch.rand.html


In [17]:
# Create a random tensors of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6187, 0.7858, 0.4428, 0.8410],
        [0.6383, 0.2355, 0.9792, 0.5996],
        [0.9098, 0.1281, 0.1624, 0.1990]])

In [18]:
random_tensor.ndim

2

In [19]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### zeros and ones


In [20]:
# Create a tensor of all zeros
zeros  = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
# Use torch.range() and get deprcated message, use torch.arrange()
one_to_ten = torch.arange(start=1,end = 10, step = 1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

** Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

**Precision in computing

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor (eg. float32 or float16)
                               device = None, # what device is your tensor on
                               requires_grad = False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.LongTensor)
float_16_tensor

tensor([3, 6, 9])

In [28]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_8_tensor = float_32_tensor.type(torch.short)
int_8_tensor

tensor([3, 6, 9], dtype=torch.int16)

In [30]:
float_16_tensor * int_8_tensor

tensor([ 9, 36, 81])

### Getting information from tensors
(tensor attributes)
1. Tensors not right datatype - to get datatype from a tensor, can use "tensor.dtype "
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [31]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9839, 0.3897, 0.0722, 0.9889],
        [0.9485, 0.5687, 0.7343, 0.6067],
        [0.2759, 0.2754, 0.7898, 0.2041]])

In [32]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [33]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9839, 0.3897, 0.0722, 0.9889],
        [0.9485, 0.5687, 0.7343, 0.6067],
        [0.2759, 0.2754, 0.7898, 0.2041]])
Datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [34]:
# Create a tensor and add 100 to it
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [35]:
# Multiply tensor by 10
tensor *10

tensor([10, 20, 30])

In [36]:
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor, 10)

tensor([11, 12, 13])

# Matrix multiplication

Two main of performing multiplication in neural networks and deep learings:

1. Element-wise multiplication
2. Matrix multiplications  (dot product)

More information on multiplying matrices-https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **Outer dimesions**:
* `(2,3) @ (3,2)` ->(2,2)
* `(3,2) @ (2,3)` ->(3,3)


In [39]:
torch.matmul(torch.rand(1,10), torch.rand(10,1))

tensor([[2.0050]])

In [40]:
 # Element wise multiplication
print ( tensor,"*", tensor)
print (f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [41]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
# Matrix multiplication by hand
1*1+2*2+3*3

14

In [43]:
tensor @ tensor

tensor(14)

In [44]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]

print(value)

tensor(14)
CPU times: user 2.46 ms, sys: 76 µs, total: 2.54 ms
Wall time: 4.89 ms


In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 56 µs, sys: 9 µs, total: 65 µs
Wall time: 68.7 µs


tensor(14)

### one of the most common errors in deep learning: shape errors

In [46]:
# Shapes for matrix multiplications
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B= torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm(tensor_A, tensor_B) # torch.mm = torch.matmul

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <-inner dimesnions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")
# The matrix multiplication operation works when tensor_B is transposed

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = tensor([[ 7,  8,  9],
        [10, 11, 12]])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <-inner dimesnions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [47]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [48]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [49]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

## Finding the min, max, mean, sum,etc (tensor aggregation)

In [50]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [51]:
# Finde the mean - note: the torch.mean() function requires a tensor of a float 32 datatype to work
torch.min(x),
x.max(),
torch.mean(x.type(torch.float32)),
x.type(torch.float32).mean(),
torch.sum(x),
x.sum()

tensor(460)

Finding the positional min and max

In [52]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minmum value occurs
x.argmin() , x[0]

(tensor(0), tensor(1))

In [53]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax(), x[9]

(tensor(9), tensor(91))

## Reshaping, stacking , squeezing and unsqueezing tensors

* Reshaping  - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other(vstack) or side by side (hstack)
* Squeeze - remove all '1' dimensions from a tensor
* Unsqueez - add a '1' dimesion to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped in a certain way)


In [54]:
# Let's create a tensor
x = torch.arange(1., 13)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [55]:
# Add an extra dimension
x_reshaped = x.reshape(1,12)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [56]:
x_reshaped2 = x_reshaped.reshape(6,2).reshape(3,4)
x_reshaped2

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [57]:
# Change the view
z = x.view(1,12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [58]:
# changing z  changes x (becasue a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [59]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked


tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [60]:
# torch.squeeze() - remove all single dimesnsions from a target tensor
print(f'previous tensor: {x_reshaped}')
print(f'previous shape: {x_reshaped.shape}')

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor:{x_squeezed}')
print(f'New shape: {x_squeezed.shape}')


previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
previous shape: torch.Size([1, 12])

New tensor:tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
New shape: torch.Size([12])


In [61]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')


Previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
Previous shape: torch.Size([12])

New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
New shape: torch.Size([1, 12])


In [62]:
# torch.permute - rearrange the dimensions of a target tensor in a specified order
pic = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]
 # Permute the orignial tensor to rearrange the axis (or dim) order
pic_permuted = pic.permute(2, 0 ,1 ) # shifts axis 0->1, 1->2, 2->0

print(f'Previous shape: {pic.shape}')
print(f'New shape: {pic_permuted.shape}') # [color_channels, height, width]




Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [63]:
pic[0, 0, 0] = 728218
pic[0, 0, 0], pic_permuted[0, 0, 0]


(tensor(728218.), tensor(728218.))

##Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy


In [64]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [65]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [66]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [67]:
# Let's index on the most inner bracket (last dim)
x[0][2][2]

tensor(9)

In [68]:
# You can also use ":" to select "all" of the target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [69]:
# Get all value of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [70]:
# Get all value of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [71]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [72]:
# Index on x to return 9
print(x[0, 2, 2])


tensor(9)


In [73]:
# index on x to retrun 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

##PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library .

And becos of this, PyTorch has functionality to interact with it.

*Data is NumPy, want in PyTorch tensor-> 'torch.from_numpy(ndarray)'
*PyTorch tensor ->NumPy -> torch.Tensor.numpy()

In [107]:
 # NumPy array to tensor
 import torch
 import numpy as np

 array = np.arange(1.0, 8.0)
 tensor = torch.from_numpy(array)
 #when coverting from numpy->pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwised
 array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [109]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array
tensor = tensor.type(torch.float32)
array,tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [82]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [112]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor = tensor +1
tensor, numpy_tensor

(tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

'start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data ->again ->again ->again...'

To reduece the randomness in neural networks and PyTorch comes to the concept of a **random seed**.

Essentially what the random seed does is 'flavour' the randomness.


In [116]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.3916, 0.4751, 0.0499, 0.4524],
        [0.0055, 0.5805, 0.8628, 0.6268],
        [0.4715, 0.3081, 0.7199, 0.1808]])
tensor([[0.0750, 0.9336, 0.6022, 0.1568],
        [0.8990, 0.9565, 0.2514, 0.2135],
        [0.5533, 0.1557, 0.0886, 0.7057]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [122]:
# Let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(1,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(1,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593]])
tensor([[True, True, True, True]])


Extra resources of reproducbility:

https://pytorch.org/docs/stable/notes/randomness.html

https://en.wikipedia.org/wiki/Random_seed

## Running tensros and PyTorch objects on the GPUs (and making faster computations )

GPUs = faster computation on numbers ,

thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).



### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU. (options to upgrade as well)

2. Use your own GPU - takes a little bit of setup and requires the investments of purchasing a GPU, there's lots of options...see this post for what options to get: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/

3. Use cloud computing - GCP , AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this , refer to PyTorch setup documentations :
https://pytorch.org/get-started/locally/






In [2]:
!nvidia-smi

Tue Aug  1 01:50:22 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [3]:
# check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU is availabe, else default to CPU

In [5]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [7]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU.
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

---------------------------------------------------------------------------
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()


TypeError                                 Traceback (most recent call last)
<ipython-input-9-b7da913938a5> in <cell line: 2>()
      1 # If tensor is on GPU, can't transform it to NumPy
----> 2 tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [12]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_CPU = tensor_on_gpu.cpu().numpy()
tensor_back_on_CPU

array([1, 2, 3])

In [13]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')